In [ ]:
#import dependencies
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.linear_model import LogisticRegression

In [ ]:
data = pd.read_csv('/content/Credit Default.csv')

In [ ]:
data.shape

(2000, 5)

In [ ]:
data.head()

,Income,Age,Loan,Loan to Income,Default
0,66155.92510,59.017015,8106.532131,0.122537,0
1,34415.15397,48.117153,6564.745018,0.190752,0
2,57317.17006,63.108049,8020.953296,0.139940,0
3,42709.53420,45.751972,6103.642260,0.142911,0
4,66952.68885,18.584336,8770.099235,0.130990,1


In [ ]:
data.tail()

,Income,Age,Loan,Loan to Income,Default
1995,59221.04487,48.518179,1926.729397,0.032535,0
1996,69516.12757,23.162104,3503.176156,0.050394,0
1997,44311.44926,28.017167,5522.786693,0.124636,1
1998,43756.05660,63.971796,1622.722598,0.037086,0
1999,69436.57955,56.152617,7378.833599,0.106267,0


In [ ]:
data.describe()

,Income,Age,Loan,Loan to Income,Default
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,45331.600018,40.927143,4444.369695,0.098403,0.141500
std,14326.327119,13.262450,3045.410024,0.057620,0.348624
min,20014.489470,18.055189,1.377630,0.000049,0.000000
25%,32796.459720,29.062492,1939.708847,0.047903,0.000000
50%,45789.117310,41.382673,3974.719418,0.099437,0.000000
75%,57791.281670,52.596993,6432.410625,0.147585,0.000000
max,69995.685580,63.971796,13766.051240,0.199938,1.000000


In [ ]:
data.isnull().sum()

Income            0
Age               0
Loan              0
Loan to Income    0
Default           0
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Income          2000 non-null   float64
 1   Age             2000 non-null   float64
 2   Loan            2000 non-null   float64
 3   Loan to Income  2000 non-null   float64
 4   Default         2000 non-null   int64  
dtypes: float64(4), int64(1)
memory usage: 78.2 KB


In [ ]:
x=data.drop(['Default'],axis=1)
y = data['Default']

In [ ]:
print(x)

           Income        Age         Loan  Loan to Income
0     66155.92510  59.017015  8106.532131        0.122537
1     34415.15397  48.117153  6564.745018        0.190752
2     57317.17006  63.108049  8020.953296        0.139940
3     42709.53420  45.751972  6103.642260        0.142911
4     66952.68885  18.584336  8770.099235        0.130990
...           ...        ...          ...             ...
1995  59221.04487  48.518179  1926.729397        0.032535
1996  69516.12757  23.162104  3503.176156        0.050394
1997  44311.44926  28.017167  5522.786693        0.124636
1998  43756.05660  63.971796  1622.722598        0.037086
1999  69436.57955  56.152617  7378.833599        0.106267

[2000 rows x 4 columns]


In [ ]:
print(y)

0       0
1       0
2       0
3       0
4       1
       ..
1995    0
1996    0
1997    1
1998    0
1999    0
Name: Default, Length: 2000, dtype: int64


In [ ]:
data['Default'].value_counts()

0    1717
1     283
Name: Default, dtype: int64

In [ ]:
data.groupby('Default').mean()

,Income,Age,Loan,Loan to Income
Default,,,,
0,45318.317216,43.321309,3978.171771,0.088270
1,45412.188607,26.401412,7272.856747,0.159879


In [ ]:
#train_test_model
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=2)

In [ ]:
print(x_train.shape,x_test.shape,x.shape)

(1600, 4) (400, 4) (2000, 4)


In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(x_train,y_train)

LogisticRegression()

In [ ]:
model.intercept_

array([-0.00067592])

In [ ]:
model.coef_

array([[-5.57990472e-05, -1.43244133e-01,  9.16426631e-04,
        -7.46730134e-05]])

In [ ]:
x_train_prediction = model.predict(x_train)
x_train_accuracy = accuracy_score(x_train_prediction,y_train)

In [ ]:
print(x_train_accuracy)

0.91625


In [ ]:
x_test_prediction = model.predict(x_test)
x_test_accuracy=accuracy_score(x_test_prediction,y_test)

In [ ]:
print(x_test_accuracy)

0.9


In [ ]:
y_prediction = model.predict(x_test)

In [ ]:
y_prediction

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,

In [ ]:
confusion_matrix(y_prediction,y_test)

array([[332,  31],
       [  9,  28]])

In [ ]:
accuracy_score(y_prediction,y_test)

0.9

In [ ]:
classification_report(y_prediction,y_test)

'              precision    recall  f1-score   support\n\n           0       0.97      0.91      0.94       363\n           1       0.47      0.76      0.58        37\n\n    accuracy                           0.90       400\n   macro avg       0.72      0.84      0.76       400\nweighted avg       0.93      0.90      0.91       400\n'

In [ ]:
#prediction_model
input_data =[40654.89254,55.49685254,4755.82528,0.116980392]
#changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

#reshape the arrat as are predicting for one instance
input_data_reshape = input_data_as_numpy_array.reshape(1,-1)

std_input = input_data_reshape

prediction = model.predict(std_input)

print(prediction)
if (prediction[0]==0):
    print('Defult')
else:
     print('Not Defult')

[0]
Defult


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
